### ISSUE TITLE
DOCS: IMDG Reference Manual: “Distributed Data Structures: Overview of HZ Distributed objects”- not working code example

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/imdg-docs#184]
https://docs.hazelcast.com/imdg/5.0-SNAPSHOT/data-structures/overview.html

Example Distributed Object Code: Part of class is missed - example couldn't be used.
Reproduces with Google Chrome and Mac Safari.
see screenshot
<img width="895" alt="Screen Shot 2021-04-21 at 5 04 51 PM" src="https://user-images.githubusercontent.com/67485185/115567310-cf967a80-a2c3-11eb-93ab-164f1fbc2f4e.png">

**Comment by JakeSCahill** [comment]
I believe this may be intentional as we have tagged the content that we want to show here: https://github.com/hazelcast/imdg-docs/blob/master/docs/modules/ROOT/examples/ExampleDOL.java

I suppose we are assuming that the reader knows Java well enough to add this to a class. But then again the full example shows that the class must implement `DistributedObjectlistener`. So maybe we should display the full example here?

**Comment by Serdaro** [comment]
Fixed with the above commits.
