### ISSUE TITLE
Search results link to latest version

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/imdg-docs#187]
Selected 3.12.12 version docs but when we search any other information then search result shows 4.2(latest) docs results.

**Comment by JakeSCahill** [comment]
We only index the latest version of the docs at the moment. This was a concious decision because it avoids having a huge index for similar content.

As a workaround, users can search the docs and use the version dropdown to view the same page for a different version:
![image](https://user-images.githubusercontent.com/45230295/115725116-78eb7800-a379-11eb-9208-a6f90240f798.png)

**Comment by ilkerkorkut** [comment]
Thank you @JakeSCahill , If this is a concious decision, then you can close this issue. But, it's difficult to search under the selected version. As a user, I couldn't expect everytime to select a previous version after the search.

**Comment by JakeSCahill** [comment]
I'll leave this open for now @ilkerkorkut. It seems like something we will want to do in the future.

**Comment by sertugkaya** [comment]
if a user: 
- selects an older version of docs 
- does a text search
- click on a search result
That takes the user back to the latest version again.

Even if I try to go to the section I'm looking for on the latest version of the docs, and then try to switch back to the older version, it takes me back to the homepage of the older version doc instead of that section

**Comment by JakeSCahill** [comment]
Fixed.
